version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    - ./data-init/pg/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: postgrespassword
    healthcheck:
      test: "pg_isready -q -h postgres"
      interval: 10s
      timeout: 5s
      retries: 30
  redis:
    image: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
  hge-instant:
    image: hasura/graphql-engine:latest
    ports:
    - "8010:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    environment:
      HASURA_GRAPHQL_EE_LICENSE_KEY: eyJhbGciOiJSUzI1NiIsImtpZCI6IjEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJIYXN1cmEiLCJzdWIiOiJjaHJpcy0xIiwiZXhwIjoxNzU2NTgyNDUyLCJpYXQiOjE2NjE5NzQ0NTIsImp0aSI6ImU4NmU1YTU0LWFkM2ItNDllNi05OGNhLWFiMzRiMGE1MGY4ZiJ9.RIlbx2QnDF5qbX7HUUm60Ei-HvaUyGdAWZqn6RLbm0vl6vRoxEVJ3yhozTqovpACSvntw2ADKtYkYcAC0SkYc6OvT1RO74H8soiVY25c2upbqvm6cXsLqaaHnh37_HJbFUHlD93hGcjQUUCQPnp0ETY51s5WxOj4mQlOXRBXmXKyJFmJnH7r5ezVoXQ9TvyQOks8a7XbWAjWBnzeK0HQ4u8Ap5Y5lOs9u-WGeZyhIj6GOkR0Jl4RrOXTXnuIsw60VXiE5gNutIt_uY5UTpm7LT8n5LrlCj8AwUJ7ZSCQjAd6-T_CcisH7xOurajhXW5GrL0GMnffPOxejQAQQAMZarxAxU_kRcQrT6XNcAvXZ6q5sAHhDyyDDornld5dPSRspA8wUV8Y3nnz6WWqvI9TXxxV9CmGvBd1AH-sQMlRp12uxkaLrz8IEYK2Zv1Nj-XJaCFActSuBVSAf-MV2lMdZEx_iBQKk57Ze0l3G20AhVwnVufsEWf1VpjRTxR40cqR
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      ## The metadata database for this Hasura GraphQL project. Can be changed to a managed postgres instance
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/hge_metadata_instant
      PG_DB_URL: postgres://postgres:postgrespassword@postgres:5432/chinook_music
      DB_URL: postgres://postgres:postgrespassword@postgres:5432/chinook_music
      CHINOOK_DB_URL: postgres://postgres:postgrespassword@postgres:5432/chinook

      ## Optional settings:
      #HASURA_GRAPHQL_REDIS_URL: redis://redis:6379
      #HASURA_GRAPHQL_RATE_LIMIT_REDIS_URL: redis://redis:6379
      # enable prometheus metrics endpoint
      HASURA_GRAPHQL_ENABLED_APIS: metadata,graphql,config,metrics
      #ecure the prometheus metrics endpoint
      HASURA_GRAPHQL_METRICS_SECRET: metricssecret
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: true
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: true
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: streaming_subscriptions
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      # HASURA_GRAPHQL_READ_REPLICA_URLS: postgres://postgres:postgrespassword@postgres:5432/postgres
    healthcheck:
      test: bash -c ':> /dev/tcp/0.0.0.0/8080' || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
  hge-orders:
    image: hasura/graphql-engine:latest
    ports:
    - "8014:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    environment:
      HASURA_GRAPHQL_EE_LICENSE_KEY: eyJhbGciOiJSUzI1NiIsImtpZCI6IjEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJIYXN1cmEiLCJzdWIiOiJjaHJpcy0yIiwiZXhwIjoxNzU2NTgyNTQ1LCJpYXQiOjE2NjE5NzQ1NDUsImp0aSI6IjJmMGVlOGIyLTg4OTgtNGFjYi1iMzU1LTliYzljNTQ1ZjExMiJ9.WDFHLAxPzxPQQsRRpPg2nY5d69U6Zk-4cBHiEqFrO8pe9N5opCrMJeRw5_ohtxgbobB-PKDn4CQ8DKlSe9LKpBErV1tTwAWMPOyYHSHD0lAvP_uUcSFLe0WC03jfRK6ycyfP0SErU-kSlnC8EaTS8Kav97nkHF-fK3qOBdeoG_I4XXPxuAsJYFQ8Q3bF6PdUVA2I8Wfp3Z33MBjq1Ygef3orWJv3StKmqyQoJgcCOZE5fILlbqzfdvuh1gpbWy4C8SGIKNV22eEISTr5b43CtUhaEQrR8TzdtcwB6smswzgtiLxx_GvWlXHjCcqaithow68Y_5ctHCGuBQCyoG3Ld4pdxUKXaqdcMqvVRyRd_DV2kLmkWlGToKnAdIFrm5OdXDi1vk6aMzva3uf2pQzkELWuAnUFA-Rdg3WyLcOjUDIam16Bb7EB56m_tgElQFww96dKKUgkFOm6d4ycT62E5DUUQIOc1wTnUBVc5QvWbqwteKVb9rnHqgr-L6jALaDL
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      ## The metadata database for this Hasura GraphQL project. Can be changed to a managed postgres instance
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/hge_metadata_orders
      HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT: 30

      ## Optional settings:
      HASURA_GRAPHQL_REDIS_URL: redis://redis:6379
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: true
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: true
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: streaming_subscriptions
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
    healthcheck:
      test: bash -c ':> /dev/tcp/0.0.0.0/8080' || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
  hge-crm:
    image: hasura/graphql-engine:latest
    ports:
    - "8013:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    environment:
      HASURA_GRAPHQL_EE_LICENSE_KEY: eyJhbGciOiJSUzI1NiIsImtpZCI6IjEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJIYXN1cmEiLCJzdWIiOiJjaHJpcy0zIiwiZXhwIjoxNzU2NTgyNTkxLCJpYXQiOjE2NjE5NzQ1OTEsImp0aSI6IjkyODEwMTkyLTI1ODEtNDdjYy04ODY1LTJlYWQyNzcxYWI4NCJ9.d_LSUNtJhTi3iTpQuP4JJui4eIDfmIlgBAcUJpuNF6cdtucok95c5MJoh2w7jHULqLbksZwXqUvaHihajDLOVy4crqrUvaoaL85rzDc3_3_LusUnk_Fm-l4c6GVAtQLayYQx67w3cVy_Hvbe7Wumk1mMMHZWL8GZcNDE7MmAIo2RD40fpofnfdJHfYw8QC1GD3oLlMdU20MS6uvBh1Ld4rlrY6uE1XNGQfdBk2Y_rEHwQ9_MVvjHZLOxJ7Vg3bzTPFmTjUuA9DMea4qFoZBE4PNzqxciCMWEU4Y7WhBpJDtfanN80e44kNAsOu3xAhvxscpquxrFDH4CV96i1kjtgtOZfvg1gvjHkKfXrTQCcfqTdcWlC3I8rw1V94ByePXQxJdvQj6U8i_DzynKqtW-fwsOh67J3KTqKILUxW_wRXcIqlM-a9z4zGWh02i8wQc5ihMiI0RMiC1Nl0ZiHj8UOc-NwWv-CMdxCu4FfFDM9DfTHFp8FYaxqrQ0CafSJAIC
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      ## The metadata database for this Hasura GraphQL project. Can be changed to a managed postgres instance
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/hge_metadata_crm
      HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT: 30

      ## Optional settings:
      HASURA_GRAPHQL_REDIS_URL: redis://redis:6379
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: true
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: true
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: streaming_subscriptions
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
    healthcheck:
      test: bash -c ':> /dev/tcp/0.0.0.0/8080' || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
  hge-hr:
    image: hasura/graphql-engine:latest
    ports:
    - "8012:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    environment:
      HASURA_GRAPHQL_EE_LICENSE_KEY: eyJhbGciOiJSUzI1NiIsImtpZCI6IjEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJIYXN1cmEiLCJzdWIiOiJjaHJpcy00IiwiZXhwIjoxNzU2NTgyNjQwLCJpYXQiOjE2NjE5NzQ2NDAsImp0aSI6ImQ1MmI4YjI1LTAzZTUtNDhlMS05OWJhLTkwYmVjZTgwM2Q0ZiJ9.LFi1pshXS2jkbIC2cXI-MY8ODykaMryTj3_4w_yMK5Vb0D7iEE12qUODHOcCKqtDbNt3g5jS09ZTr5Biu3aBSlZ2sVuNcNU5YqGxLZ1kpQCzdEcA1ZbEjLUdGfkjrXGJpPJxcW6jW_0dg00b5UC2uZU41U2DGJI6yoz2d1V1QCvkY99iGXEN3ZBRtTvkigIvxeMd1Ogk3BayY42ygbWdnbpldPqZKjxcHUEGReREpixWeslg5XjSFhYxsR00dba2nXx1H7weuI7w6VXlOvagPCGF4vJy656M1vAF-LkZ8JWjlBlzUI5lItq7hbTqm2chz3DiRnq4hvxLBTOji76ytNcH36d22hFqiJ339GjMIu_LrxEFrzi7wdCNOhUNfa_ojuQPnyg3Cifc-QyKoUmleUEg3l1KGbMfy7kYgsvY14STq_XOpYqVCXANKJ9GjtOBd7E9eDg89Gji3IYu9DEq3-XrFH9zn_cCOSPpfzKjis5_MNtYDLXsq72mPCpbAsD4
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      ## The metadata database for this Hasura GraphQL project. Can be changed to a managed postgres instance
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/hge_metadata_hr
      HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT: 30

      ## Optional settings:
      HASURA_GRAPHQL_REDIS_URL: redis://redis:6379
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: true
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: true
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: streaming_subscriptions
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets

      SENDGRID_API_KEY_HEADER: Bearer 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
    healthcheck:
      test: bash -c ':> /dev/tcp/0.0.0.0/8080' || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
  hge-main:
    image: hasura/graphql-engine:latest
    ports:
    - "8011:8080"
    depends_on:
      postgres:
          condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    environment:
      HASURA_GRAPHQL_EE_LICENSE_KEY: eyJhbGciOiJSUzI1NiIsImtpZCI6IjEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJIYXN1cmEiLCJzdWIiOiJjaHJpcy01IiwiZXhwIjoxNzU2NTgyNjk3LCJpYXQiOjE2NjE5NzQ2OTcsImp0aSI6IjllZGFhOTU1LWY2NzItNDYzOS1hYzhhLTNiODQxYjdmNzI2NSJ9.FgSgikkmWYPwzmRRC_Ydwln_zW5ocXLHYG9K00d7Ka1qeL4oFlkrRLPWMsbijNj4ZaYCFNXMmc1Nb6gReNFfZv0osgGGcZFYeUNmF_4WXiNCQnTZC0hHpCkvUdOUttmP2Yz200dxG3kS_yBpu2Z_qFoe-7P8dsH19F33AwhOEG014CDpAuAxHAziTEu4tBfH-GxU_SNwP83VhuJSer7yWzjjGTxu4FVTFNxU4Bn1wy0W1NSx9JHvB23SMxhfPHwfYviKTHY84La9Dp11U8Imi_U09aLe8rtezV-Rd2zQl-rv2xFlwSpPR2DtjMxBHYkitljJa_N5Ln4QYM8wYpPRdoMb8lL87BEXEdnBp5p91LCcIe_WMj7zS1b7dMtDlazbVksQ_O2xDdayrylFMlaHPlEVnZjz37ehO7DcNVXI5WwT-krATSrhrzmfAwp8lG6a5qvnhGGQ0JXMm9y2q7EcNuq29lbIayWYjCTxrp4-E64g_YTg45fJ85jIMZbRWzne
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      ## The metadata database for this Hasura GraphQL project. Can be changed to a managed postgres instance
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/hge_metadata_main
      HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT: 30

      ## Optional setting
      HASURA_GRAPHQL_REDIS_URL: redis://redis:6379
      HASURA_GRAPHQL_JWT_SECRET: |
        {
          "key": "hasura-jwt-hs384-superduperreallyreallystrongsecret",
          "claims_map": {
            "x-hasura-allowed-roles": {
              "path": "$$.allowed-roles"
            },
            "x-hasura-default-role": {
              "path": "$$.allowed-roles[0]"
            },
            "x-hasura-user-id": {
              "path": "$$.uid"
            }
          },
          "type": "HS384"
        }
      HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS: true
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: true
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: true
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: streaming_subscriptions
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
    healthcheck:
      test: bash -c ':> /dev/tcp/0.0.0.0/8080' || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db_data:
